name: CD - Deploiement sur Self-Hosted Runner

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on:
      - self-hosted
      - linux
      - x64

    steps:
      - name: Recuperation du code
        uses: actions/checkout@v4

      - name: Deploiement vers Nginx local
        run: |
          echo "<h1>LABO-AIS deploye automatiquement par GitHub Actions</h1>" > /var/www/labo-ais/index.html
          echo "<p>Deploiement effectue depuis le Self-Hosted Runner.</p>" >> /var/www/labo-ais/index.html
